### ISSUE TITLE
[1.0.3] [Carol] Jumping off walls will sometimes kick you downward

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#136]
Submitter: aidenpons
I really have no clue what's causing this, but when on foot or on bike, sometimes jumping off a wall will cause the player to fall much faster than they should. Normally it's just the effects of gravity, but sometimes you fall down really quickly, as if you'd been falling for some time (which you haven't).

**Comment by TreyLina** [comment]
I have footage of this:  https://www.youtube.com/watch?v=7ZOSY3FiF64
It's when you touch the ceiling.

**Comment by SpaceyStrife** [comment]
Fixed for 1.0.4.

**Comment by TreyLina** [comment]
I just got 1.0.4, and this still happens. I can trigger it constantly. Reopen please.

**Comment by SpaceyStrife** [comment]
Where does it happen? I've tested it in several different corners and it no longer happens.

**Comment by TreyLina** [comment]
If you jump to a ceiling (and hit it with your head from below), then press jump again, it will always shoot you downward. It shows in the video clip: https://www.youtube.com/watch?v=7ZOSY3FiF64 

In other words, hitting the ceiling causes it to happen all the time.

*EDIT: I'm an idiot, It is fixed. I thought I had upgraded to 1.0.4, but apparently not.*

**Comment by SpaceyStrife** [comment]
I've just tried doing the same thing in the latest build in that same location and I can't get it to trigger.

**Comment by TreyLina** [comment]
Okay, nevermind. I'm an idiot, It is fixed. I thought I had upgraded to 1.0.4, but apparently not. It can be closed now. I'll try and combat my tunnel vision to prevent this from happening in the future.

**Comment by SpaceyStrife** [comment]
It's okay, it happens!
